import classes from './Rive.module.css'

const ItemData = [
	{
		swap: false,
		title: 'Spotify',
		text: 'This is a copy of the home page for the well-known Spotify online app, which is my favorite music streaming service.',
		disabled: true,
		link: '',
        fade: 'fade-up',
        stateMachine: 'State Machine 1',
        hoverState: '',
        animation: 'Animation 1',
        src: 'spotify.riv',
        cssClass: classes.spotify,
	},
	{
		swap: true,
		title: 'Chat',
		text: 'A conversation app with a stylish appearance and modern design. Made with Material UI.',
		disabled: false,
		link: 'https://chat-app-dashboard.vercel.app/',
        fade: 'fade-left',
        stateMachine: 'State Machine 1',
        hoverState: '',
        animation: 'Animation 1',
        src: 'chat.riv',
        cssClass: classes.item,
	},
	{
		swap: false,
		title: 'Earth',
		text: 'I adore the stars and everything space-related. This website provides details about each planet in our solar system.',
		disabled: true,
		link: '',
        fade: 'fade-right',
        stateMachine: '',
        hoverState: '',
        animation: 'Animation 1',
        src: 'planet.riv',
        cssClass: classes.item,
	},
	{
		swap: true,
		title: 'Weather',
		text: 'Everybody requires their own weather app. A web application that generates local weather reports every day and is easy to maintain.',
		disabled: true,
		link: '',
        fade: 'fade-down',
        stateMachine: 'State Machine 1',
        hoverState: 'isPressed',
        animation: 'Raining',
        src: 'cloud.riv',
        cssClass: classes.item,
	},
];

export default ItemData